
version: 2
jobs:
  modify-and-deploy:
    docker:
      # see https://hub.docker.com/r/circleci/python/tags/
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run: |
          set -e
          sudo pip install bs4
          sudo pip install requests
      - run: ./modify.py
      - run: |
          set -e
          curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&version=6.32.0&source=github-rel'
          sudo dpkg -i cf-cli_amd64.deb
          cf install-plugin https://github.com/govau/autopilot/releases/download/0.0.5-venapp/autopilot-linux -f
          ./deploy.sh
workflows:
  version: 2
  modify-and-deploy:
    jobs:
      - modify-and-deploy
